grpc:
  # grpc client相关配置
  client:
    # 服务名（不同服务名可对应不同配置）
    grpc-alg-server:
      # 服务端地址
      address: 'static://172.27.97.206:8081'
      # 是否开启保持连接（长连接）
      enableKeepAlive: true
      # 保持连接时长（默认20s）
      keepAliveTimeout: 20s
      # 没有RPC调用时是否保持连接（默认false，可禁用避免额外消耗CPU）
      keepAliveWithoutCalls: false
      # 客户端负载均衡策略(round_robin（默认）, pick_first)
      defaultLoadBalancingPolicy: round_robin
      # 通信类型
      # plaintext | plaintext_upgrade | tls
      # 明文通信且http/2 | 明文通信且升级http/1.1为http/2 | 使用TLS（ALPN/NPN）通信
      negotiationType: plaintext

jwt:
  key: 'fe72fd8d724713558db100c50e42497632bcc0d570850231bbc9f9a0b4b804e1'
  expiration: 1800000

user:
  min-username-length: 2
  max-username-length: 8
  min-password-length: 8
  max-password-length: 20

spring:
  application:
    name: 'StaticAnalyzer'
  redis:
    database: 0
    host: localhost
    port: 6379